### PR TITLE
Adds Klasa-Bot-Plugin

### PR DESCRIPTION
**Pull request by Skillz4Killz**
Adds the all purpose klasa bot plugin providing bots with hundreds of features.

### CODE REVIEW

**Comment by tech6hutch** [comment]
In my opinion, this plugin encourages people to make generic bots using other people's code, a problem prevalent in the Discord bot community. The auto-update sounds nice, but ultimately I think customization is more important, and should be encouraged over giving every bot the same features.

The custom commands system, however, is a nice feature, but I find it rather strange that it's only available bundled in with this plugin.

**Comment by Skillz4Killz** [comment]
In my opinion, using open source code in your own bot is not a problem that's the point of it being open source. The point of the plugin is to be an all-purpose plugin that provides everything for new developers just starting out.

For new developers, they don't care for customization or having 20 plugins or doing it themselves. It's about the simplest way to get it working for them. This is why I already have approximately 56 users of the plugin at this time. Its a simple plug and play plugin that provides them everything they could want for their own bots.

Customization is not at all hindered as with klasa anyone that wants to customize can easily transfer and customize. This plugin is targeted to the beginner developers starting out. This plugin is not meant for every developer.

P.S. If you think the custom command system can work as a separate plugin feel free to take it and make it for anyone that only wants it. Im also working on adding in a complete music module into it as well and if you like you can also make that separate. Open source! <3

**Comment by kyranet** [comment]
Closing due to the reasons mentioned by @tech6hutch, I don't think I will accept a plugin that merely adds all pieces from klasa-pieces with the risk of being out of date easily. Users should always copy their pieces from klasa-pieces.

A useful plugin related to your project that I would accept, is a CLI one that fetches the pieces from GitHub and via an interactive menu, it downloads the pieces into their respective folders.

**Comment by tech6hutch** [comment]
A piece fetch command would be very cool, agreed. I think Komada had one in core for a while (but it wasn't interactive). A Klasa one would be a good fit for Klasa Pieces.

**Pull request closed without merging**
